# Generated by Django 4.0.4 on 2022-05-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_cadeira_linguagem_professor_alter_publicacao_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Educacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=50)),
                ('local', models.CharField(max_length=35)),
                ('periodo', models.CharField(max_length=15)),
                ('logotipo', models.ImageField(upload_to='')),
            ],
        ),
    ]
