# Generated by Django 4.0.4 on 2022-05-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_educacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Educacao',
        ),
        migrations.AlterField(
            model_name='publicacao',
            name='imagem',
            field=models.ImageField(upload_to=''),
        ),
    ]
