# Generated by Django 4.0.4 on 2022-05-17 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_pessoa_delete_cadeira_delete_linguagem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('ano', models.IntegerField()),
                ('semestre', models.CharField(max_length=2)),
                ('ects', models.IntegerField()),
                ('ano_letivo', models.IntegerField()),
                ('topicos_abordados', models.TextField()),
                ('ranking', models.IntegerField()),
                ('link_cadeira', models.CharField(max_length=1000)),
                ('docente_teorica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.professor')),
                ('docentes_praticas', models.ManyToManyField(related_name='professor_pratica', to='portfolio.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('descricao', models.CharField(max_length=500)),
                ('imagem', models.ImageField(upload_to='static/portfolio/images')),
                ('anoRealizacao', models.IntegerField()),
                ('linkGitHub', models.CharField(max_length=1000, null=True)),
                ('linkYt', models.CharField(max_length=1000, null=True)),
                ('tecnologias', models.CharField(max_length=2000)),
                ('participantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('descricao', models.TextField(max_length=50)),
                ('cadeira', models.ManyToManyField(to='portfolio.cadeira')),
                ('projetos', models.ManyToManyField(to='portfolio.projeto')),
            ],
        ),
        migrations.AddField(
            model_name='cadeira',
            name='projetos',
            field=models.ManyToManyField(to='portfolio.projeto'),
        ),
    ]
