# Generated by Django 4.0.4 on 2022-05-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_professor_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('descricao', models.TextField(max_length=60)),
                ('imagem', models.ImageField(upload_to='static/portfolio/images')),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
