# Generated by Django 4.0.4 on 2022-05-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_interesse_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
    ]
