# Generated by Django 4.0.4 on 2022-05-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_alter_projeto_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(max_length=80),
        ),
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('anoRealizacao', models.IntegerField()),
                ('sumario', models.CharField(max_length=500)),
                ('link_relatorio', models.CharField(max_length=1000)),
                ('linkGitHub', models.CharField(blank=True, max_length=1000, null=True)),
                ('linkYt', models.CharField(blank=True, max_length=1000, null=True)),
                ('autor', models.ManyToManyField(to='portfolio.pessoa')),
                ('orientador', models.ManyToManyField(to='portfolio.professor')),
            ],
        ),
    ]
