# Generated by Django 4.0.4 on 2022-05-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_professor_nome_alter_projeto_titulo_tfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('descricao', models.TextField(max_length=1000)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('descricao', models.TextField(max_length=1000)),
                ('imagem', models.ImageField(upload_to='static/portfolio/images')),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('acrónimo', models.CharField(blank=True, max_length=10)),
                ('anoCriacao', models.IntegerField()),
                ('criador', models.CharField(max_length=80)),
                ('logotipo', models.ImageField(upload_to='static/portfolio/images')),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('descricao', models.TextField(max_length=1000)),
            ],
        ),
    ]
