# Generated by Django 4.0.4 on 2022-05-19 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_laboratorio_noticia_tecnologia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tecnologia',
            old_name='acrónimo',
            new_name='acronimo',
        ),
    ]
