# Generated by Django 4.0.4 on 2022-05-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_tecnologiawebsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
