# Generated by Django 4.0.4 on 2022-05-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_publicacao_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacao',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
