# Generated by Django 4.0.4 on 2022-05-23 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_cadeira_linguagens_alter_cadeira_projetos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='link_lusofona',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='docente_teorica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='docentes_praticas',
            field=models.ManyToManyField(related_name='professor_pratica', to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='autor',
            field=models.ManyToManyField(related_name='autor', to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='tfc',
            name='orientador',
            field=models.ManyToManyField(related_name='orientador', to='portfolio.pessoa'),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
