# Generated by Django 4.0.4 on 2022-05-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_pessoa_link_lusofona_alter_cadeira_docente_teorica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('nivel', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='competencia',
            name='cadeira',
            field=models.ManyToManyField(blank=True, to='portfolio.cadeira'),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='descricao',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='competencia',
            name='projetos',
            field=models.ManyToManyField(blank=True, to='portfolio.projeto'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='participantes',
            field=models.ManyToManyField(blank=True, to='portfolio.pessoa'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(blank=True, to='portfolio.tecnologia'),
        ),
    ]
