# Generated by Django 4.0.4 on 2022-05-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_lingua_alter_competencia_cadeira_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lingua',
            name='nivel',
            field=models.CharField(max_length=30),
        ),
    ]
