# Generated by Django 4.0.4 on 2022-05-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_pontuacaoquizz_delete_quizz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='static/portfolio/images'),
        ),
    ]
